/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Driver {
  'id' : bigint,
  'pin' : string,
  'status' : DriverStatus,
  'name' : string,
  'current_order_id' : [] | [bigint],
  'truck_plate' : string,
  'phone' : string,
  'zone_id' : bigint,
}
export interface DriverPrices {
  'large' : bigint,
  'small' : bigint,
  'medium' : bigint,
}
export type DriverStatus = { 'offline' : null } |
  { 'online' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'help_flagged' : boolean,
  'customer_phone' : string,
  'size' : TankSize,
  'created_at' : bigint,
  'payment_status' : PaymentStatus,
  'address_note' : string,
  'driver_id' : [] | [bigint],
  'payment_ref' : string,
  'completed_at' : [] | [bigint],
  'matched_at' : [] | [bigint],
  'zone_id' : bigint,
  'expired_at' : [] | [bigint],
  'idempotency_key' : string,
}
export type OrderStatus = { 'pumping' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'exception' : null } |
  { 'completed' : null } |
  { 'en_route' : null } |
  { 'matched' : null } |
  { 'accepted' : null };
export type PaymentMode = { 'always_success' : null } |
  { 'always_fail' : null } |
  { 'random' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export type TankSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface Zone {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'display_order' : bigint,
}
export interface _SERVICE {
  'acceptOrder' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createOrder' : ActorMethod<
    [bigint, TankSize, string, string, string],
    { 'ok' : { 'payment_ref' : string, 'order_id' : bigint } } |
      { 'err' : string }
  >,
  'driverLogin' : ActorMethod<
    [string, string],
    { 'ok' : { 'name' : string, 'driver_id' : bigint } } |
      { 'err' : string }
  >,
  'getDriverEarnings' : ActorMethod<
    [bigint, [] | [bigint], [] | [bigint]],
    { 'orders' : Array<Order>, 'today_total' : bigint, 'period_total' : bigint }
  >,
  'getDriverHistory' : ActorMethod<[bigint], Array<Order>>,
  'getDriverProfile' : ActorMethod<
    [bigint],
    [] | [{ 'prices' : DriverPrices, 'driver' : Driver }]
  >,
  'getIncomingOrders' : ActorMethod<[bigint], Array<Order>>,
  'getOrder' : ActorMethod<[bigint, string], [] | [Order]>,
  'getZones' : ActorMethod<[], Array<Zone>>,
  'processPayment' : ActorMethod<
    [bigint, string],
    { 'ok' : { 'status' : PaymentStatus, 'payment_ref' : string } } |
      { 'err' : string }
  >,
  'rejectOrder' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetDemo' : ActorMethod<[], { 'ok' : null }>,
  'setDriverPrices' : ActorMethod<
    [bigint, DriverPrices],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDriverStatus' : ActorMethod<
    [bigint, DriverStatus, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDriverZone' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setPaymentMode' : ActorMethod<[PaymentMode], { 'ok' : null }>,
  'updateOrderStatus' : ActorMethod<
    [bigint, bigint, OrderStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];