/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TankSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pumping' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'exception' : IDL.Null,
  'completed' : IDL.Null,
  'en_route' : IDL.Null,
  'matched' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'help_flagged' : IDL.Bool,
  'customer_phone' : IDL.Text,
  'size' : TankSize,
  'created_at' : IDL.Int,
  'payment_status' : PaymentStatus,
  'address_note' : IDL.Text,
  'driver_id' : IDL.Opt(IDL.Nat),
  'payment_ref' : IDL.Text,
  'completed_at' : IDL.Opt(IDL.Int),
  'matched_at' : IDL.Opt(IDL.Int),
  'zone_id' : IDL.Nat,
  'expired_at' : IDL.Opt(IDL.Int),
  'idempotency_key' : IDL.Text,
});
export const DriverPrices = IDL.Record({
  'large' : IDL.Nat,
  'small' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const DriverStatus = IDL.Variant({
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Driver = IDL.Record({
  'id' : IDL.Nat,
  'pin' : IDL.Text,
  'status' : DriverStatus,
  'name' : IDL.Text,
  'current_order_id' : IDL.Opt(IDL.Nat),
  'truck_plate' : IDL.Text,
  'phone' : IDL.Text,
  'zone_id' : IDL.Nat,
});
export const Zone = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'display_order' : IDL.Nat,
});
export const PaymentMode = IDL.Variant({
  'always_success' : IDL.Null,
  'always_fail' : IDL.Null,
  'random' : IDL.Null,
});

export const idlService = IDL.Service({
  'acceptOrder' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Nat, TankSize, IDL.Text, IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'payment_ref' : IDL.Text, 'order_id' : IDL.Nat }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'driverLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'name' : IDL.Text, 'driver_id' : IDL.Nat }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getDriverEarnings' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [
        IDL.Record({
          'orders' : IDL.Vec(Order),
          'today_total' : IDL.Nat,
          'period_total' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDriverHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getDriverProfile' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Record({ 'prices' : DriverPrices, 'driver' : Driver }))],
      ['query'],
    ),
  'getIncomingOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], []),
  'getOrder' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Order)], ['query']),
  'getZones' : IDL.Func([], [IDL.Vec(Zone)], ['query']),
  'processPayment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'status' : PaymentStatus,
            'payment_ref' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'rejectOrder' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetDemo' : IDL.Func([], [IDL.Variant({ 'ok' : IDL.Null })], []),
  'setDriverPrices' : IDL.Func(
      [IDL.Nat, DriverPrices],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setDriverStatus' : IDL.Func(
      [IDL.Nat, DriverStatus, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setDriverZone' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setPaymentMode' : IDL.Func(
      [PaymentMode],
      [IDL.Variant({ 'ok' : IDL.Null })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Nat, IDL.Nat, OrderStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TankSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pumping' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'exception' : IDL.Null,
    'completed' : IDL.Null,
    'en_route' : IDL.Null,
    'matched' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'help_flagged' : IDL.Bool,
    'customer_phone' : IDL.Text,
    'size' : TankSize,
    'created_at' : IDL.Int,
    'payment_status' : PaymentStatus,
    'address_note' : IDL.Text,
    'driver_id' : IDL.Opt(IDL.Nat),
    'payment_ref' : IDL.Text,
    'completed_at' : IDL.Opt(IDL.Int),
    'matched_at' : IDL.Opt(IDL.Int),
    'zone_id' : IDL.Nat,
    'expired_at' : IDL.Opt(IDL.Int),
    'idempotency_key' : IDL.Text,
  });
  const DriverPrices = IDL.Record({
    'large' : IDL.Nat,
    'small' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const DriverStatus = IDL.Variant({
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const Driver = IDL.Record({
    'id' : IDL.Nat,
    'pin' : IDL.Text,
    'status' : DriverStatus,
    'name' : IDL.Text,
    'current_order_id' : IDL.Opt(IDL.Nat),
    'truck_plate' : IDL.Text,
    'phone' : IDL.Text,
    'zone_id' : IDL.Nat,
  });
  const Zone = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'display_order' : IDL.Nat,
  });
  const PaymentMode = IDL.Variant({
    'always_success' : IDL.Null,
    'always_fail' : IDL.Null,
    'random' : IDL.Null,
  });
  
  return IDL.Service({
    'acceptOrder' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Nat, TankSize, IDL.Text, IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'payment_ref' : IDL.Text,
              'order_id' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'driverLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'name' : IDL.Text, 'driver_id' : IDL.Nat }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getDriverEarnings' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [
          IDL.Record({
            'orders' : IDL.Vec(Order),
            'today_total' : IDL.Nat,
            'period_total' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDriverHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getDriverProfile' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Record({ 'prices' : DriverPrices, 'driver' : Driver }))],
        ['query'],
      ),
    'getIncomingOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], []),
    'getOrder' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Order)], ['query']),
    'getZones' : IDL.Func([], [IDL.Vec(Zone)], ['query']),
    'processPayment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'status' : PaymentStatus,
              'payment_ref' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'rejectOrder' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetDemo' : IDL.Func([], [IDL.Variant({ 'ok' : IDL.Null })], []),
    'setDriverPrices' : IDL.Func(
        [IDL.Nat, DriverPrices],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setDriverStatus' : IDL.Func(
        [IDL.Nat, DriverStatus, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setDriverZone' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setPaymentMode' : IDL.Func(
        [PaymentMode],
        [IDL.Variant({ 'ok' : IDL.Null })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, IDL.Nat, OrderStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };