/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Zone {
    id: bigint;
    city: string;
    name: string;
    display_order: bigint;
}
export interface DriverPrices {
    large: bigint;
    small: bigint;
    medium: bigint;
}
export interface Driver {
    id: bigint;
    pin: string;
    status: DriverStatus;
    name: string;
    current_order_id?: bigint;
    truck_plate: string;
    phone: string;
    zone_id: bigint;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    help_flagged: boolean;
    customer_phone: string;
    size: TankSize;
    created_at: bigint;
    payment_status: PaymentStatus;
    address_note: string;
    driver_id?: bigint;
    payment_ref: string;
    completed_at?: bigint;
    matched_at?: bigint;
    zone_id: bigint;
    expired_at?: bigint;
    idempotency_key: string;
}
export enum DriverStatus {
    offline = "offline",
    online = "online"
}
export enum OrderStatus {
    pumping = "pumping",
    cancelled = "cancelled",
    expired = "expired",
    pending = "pending",
    exception = "exception",
    completed = "completed",
    en_route = "en_route",
    matched = "matched",
    accepted = "accepted"
}
export enum PaymentMode {
    always_success = "always_success",
    always_fail = "always_fail",
    random = "random"
}
export enum PaymentStatus {
    pending = "pending",
    success = "success",
    failed = "failed"
}
export enum TankSize {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum Variant_ok {
    ok = "ok"
}
export interface backendInterface {
    acceptOrder(driver_id: bigint, order_id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createOrder(zone_id: bigint, size: TankSize, customer_phone: string, address_note: string, idempotency_key: string): Promise<{
        __kind__: "ok";
        ok: {
            payment_ref: string;
            order_id: bigint;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    driverLogin(phone: string, pin: string): Promise<{
        __kind__: "ok";
        ok: {
            name: string;
            driver_id: bigint;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    getDriverEarnings(driver_id: bigint, start_ms: bigint | null, end_ms: bigint | null): Promise<{
        orders: Array<Order>;
        today_total: bigint;
        period_total: bigint;
    }>;
    getDriverHistory(driver_id: bigint): Promise<Array<Order>>;
    getDriverProfile(driver_id: bigint): Promise<{
        prices: DriverPrices;
        driver: Driver;
    } | null>;
    getIncomingOrders(driver_id: bigint): Promise<Array<Order>>;
    getOrder(order_id: bigint, phone_last4: string): Promise<Order | null>;
    getZones(): Promise<Array<Zone>>;
    processPayment(order_id: bigint, idempotency_key: string): Promise<{
        __kind__: "ok";
        ok: {
            status: PaymentStatus;
            payment_ref: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    rejectOrder(driver_id: bigint, order_id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetDemo(): Promise<Variant_ok>;
    setDriverPrices(driver_id: bigint, prices: DriverPrices): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setDriverStatus(driver_id: bigint, status: DriverStatus, truck_plate: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setDriverZone(driver_id: bigint, zone_id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setPaymentMode(mode: PaymentMode): Promise<Variant_ok>;
    updateOrderStatus(driver_id: bigint, order_id: bigint, new_status: OrderStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Driver as _Driver, DriverPrices as _DriverPrices, DriverStatus as _DriverStatus, Order as _Order, OrderStatus as _OrderStatus, PaymentMode as _PaymentMode, PaymentStatus as _PaymentStatus, TankSize as _TankSize } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptOrder(arg0: bigint, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOrder(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOrder(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: bigint, arg1: TankSize, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: {
            payment_ref: string;
            order_id: bigint;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, to_candid_TankSize_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, to_candid_TankSize_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async driverLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            name: string;
            driver_id: bigint;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.driverLogin(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.driverLogin(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverEarnings(arg0: bigint, arg1: bigint | null, arg2: bigint | null): Promise<{
        orders: Array<Order>;
        today_total: bigint;
        period_total: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverEarnings(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2));
                return from_candid_record_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverEarnings(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2));
            return from_candid_record_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverHistory(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverHistory(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverHistory(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverProfile(arg0: bigint): Promise<{
        prices: DriverPrices;
        driver: Driver;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomingOrders(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingOrders(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingOrders(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint, arg1: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZones(): Promise<Array<Zone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZones();
            return result;
        }
    }
    async processPayment(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            status: PaymentStatus;
            payment_ref: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.processPayment(arg0, arg1);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPayment(arg0, arg1);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectOrder(arg0: bigint, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectOrder(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectOrder(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetDemo(): Promise<Variant_ok> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDemo();
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDemo();
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDriverPrices(arg0: bigint, arg1: DriverPrices): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setDriverPrices(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDriverPrices(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDriverStatus(arg0: bigint, arg1: DriverStatus, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setDriverStatus(arg0, to_candid_DriverStatus_n29(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDriverStatus(arg0, to_candid_DriverStatus_n29(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDriverZone(arg0: bigint, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setDriverZone(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDriverZone(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPaymentMode(arg0: PaymentMode): Promise<Variant_ok> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentMode(to_candid_PaymentMode_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentMode(to_candid_PaymentMode_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: bigint, arg2: OrderStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_OrderStatus_n33(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_OrderStatus_n33(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DriverStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverStatus): DriverStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Driver_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Driver): Driver {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TankSize_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TankSize): TankSize {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        prices: _DriverPrices;
        driver: _Driver;
    }]): {
    prices: DriverPrices;
    driver: Driver;
} | null {
    return value.length === 0 ? null : from_candid_record_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    help_flagged: boolean;
    customer_phone: string;
    size: _TankSize;
    created_at: bigint;
    payment_status: _PaymentStatus;
    address_note: string;
    driver_id: [] | [bigint];
    payment_ref: string;
    completed_at: [] | [bigint];
    matched_at: [] | [bigint];
    zone_id: bigint;
    expired_at: [] | [bigint];
    idempotency_key: string;
}): {
    id: bigint;
    status: OrderStatus;
    help_flagged: boolean;
    customer_phone: string;
    size: TankSize;
    created_at: bigint;
    payment_status: PaymentStatus;
    address_note: string;
    driver_id?: bigint;
    payment_ref: string;
    completed_at?: bigint;
    matched_at?: bigint;
    zone_id: bigint;
    expired_at?: bigint;
    idempotency_key: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        help_flagged: value.help_flagged,
        customer_phone: value.customer_phone,
        size: from_candid_TankSize_n13(_uploadFile, _downloadFile, value.size),
        created_at: value.created_at,
        payment_status: from_candid_PaymentStatus_n15(_uploadFile, _downloadFile, value.payment_status),
        address_note: value.address_note,
        driver_id: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.driver_id)),
        payment_ref: value.payment_ref,
        completed_at: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.completed_at)),
        matched_at: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.matched_at)),
        zone_id: value.zone_id,
        expired_at: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.expired_at)),
        idempotency_key: value.idempotency_key
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prices: _DriverPrices;
    driver: _Driver;
}): {
    prices: DriverPrices;
    driver: Driver;
} {
    return {
        prices: value.prices,
        driver: from_candid_Driver_n21(_uploadFile, _downloadFile, value.driver)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pin: string;
    status: _DriverStatus;
    name: string;
    current_order_id: [] | [bigint];
    truck_plate: string;
    phone: string;
    zone_id: bigint;
}): {
    id: bigint;
    pin: string;
    status: DriverStatus;
    name: string;
    current_order_id?: bigint;
    truck_plate: string;
    phone: string;
    zone_id: bigint;
} {
    return {
        id: value.id,
        pin: value.pin,
        status: from_candid_DriverStatus_n23(_uploadFile, _downloadFile, value.status),
        name: value.name,
        current_order_id: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.current_order_id)),
        truck_plate: value.truck_plate,
        phone: value.phone,
        zone_id: value.zone_id
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    payment_ref: string;
}): {
    status: PaymentStatus;
    payment_ref: string;
} {
    return {
        status: from_candid_PaymentStatus_n15(_uploadFile, _downloadFile, value.status),
        payment_ref: value.payment_ref
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orders: Array<_Order>;
    today_total: bigint;
    period_total: bigint;
}): {
    orders: Array<Order>;
    today_total: bigint;
    period_total: bigint;
} {
    return {
        orders: from_candid_vec_n8(_uploadFile, _downloadFile, value.orders),
        today_total: value.today_total,
        period_total: value.period_total
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pumping: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    exception: null;
} | {
    completed: null;
} | {
    en_route: null;
} | {
    matched: null;
} | {
    accepted: null;
}): OrderStatus {
    return "pumping" in value ? OrderStatus.pumping : "cancelled" in value ? OrderStatus.cancelled : "expired" in value ? OrderStatus.expired : "pending" in value ? OrderStatus.pending : "exception" in value ? OrderStatus.exception : "completed" in value ? OrderStatus.completed : "en_route" in value ? OrderStatus.en_route : "matched" in value ? OrderStatus.matched : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): TankSize {
    return "large" in value ? TankSize.large : "small" in value ? TankSize.small : "medium" in value ? TankSize.medium : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    success: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "success" in value ? PaymentStatus.success : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offline: null;
} | {
    online: null;
}): DriverStatus {
    return "offline" in value ? DriverStatus.offline : "online" in value ? DriverStatus.online : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        status: _PaymentStatus;
        payment_ref: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        status: PaymentStatus;
        payment_ref: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n27(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
}): Variant_ok {
    return "ok" in value ? Variant_ok.ok : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        payment_ref: string;
        order_id: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        payment_ref: string;
        order_id: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        name: string;
        driver_id: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        name: string;
        driver_id: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n9(_uploadFile, _downloadFile, x));
}
function to_candid_DriverStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverStatus): _DriverStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_TankSize_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TankSize): _TankSize {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TankSize): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == TankSize.large ? {
        large: null
    } : value == TankSize.small ? {
        small: null
    } : value == TankSize.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverStatus): {
    offline: null;
} | {
    online: null;
} {
    return value == DriverStatus.offline ? {
        offline: null
    } : value == DriverStatus.online ? {
        online: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    always_success: null;
} | {
    always_fail: null;
} | {
    random: null;
} {
    return value == PaymentMode.always_success ? {
        always_success: null
    } : value == PaymentMode.always_fail ? {
        always_fail: null
    } : value == PaymentMode.random ? {
        random: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pumping: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    exception: null;
} | {
    completed: null;
} | {
    en_route: null;
} | {
    matched: null;
} | {
    accepted: null;
} {
    return value == OrderStatus.pumping ? {
        pumping: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.expired ? {
        expired: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.exception ? {
        exception: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.en_route ? {
        en_route: null
    } : value == OrderStatus.matched ? {
        matched: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
